version: '3.7'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7.2-bookworm
    restart: always

  airflow-webserver:
    image: apache/airflow:2.9.2
    build:
      context: .
    restart: always
    environment: &airflow_environment
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__CORE__FERNET_KEY: 'BFsRn4s0enzlpKLlIqYCLzkrtHDNTsYVqi_ekkzX0TI='
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: 'postgresql+psycopg2://airflow:airflow@postgres/airflow'
      AIRFLOW__CELERY__BROKER_URL: 'redis://:@redis:6379/0'
      AIRFLOW__CELERY__RESULT_BACKEND: 'db+postgresql://airflow:airflow@postgres/airflow'
      AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT: '60.0'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./requirements.txt:/requirements.txt
      - ./airflow.cfg:/opt/airflow/airflow.cfg
      - ./data:/opt/airflow/data  
      - ./models:/opt/airflow/models  
    command: webserver
    ports:
      - "8081:8080"
    depends_on:
      - airflow-init
      - postgres
      - redis

  airflow-scheduler:
    image: apache/airflow:2.9.2
    build:
      context: .
    restart: always
    environment: *airflow_environment
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./requirements.txt:/requirements.txt
      - ./airflow.cfg:/opt/airflow/airflow.cfg
      - ./data:/opt/airflow/data  
      - ./models:/opt/airflow/models  
    command: scheduler
    depends_on:
      - airflow-init
      - postgres
      - redis

  airflow-worker:
    image: apache/airflow:2.9.2
    build:
      context: .
    restart: always
    environment: *airflow_environment
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./requirements.txt:/requirements.txt
      - ./airflow.cfg:/opt/airflow/airflow.cfg
      - ./data:/opt/airflow/data  
      - ./models:/opt/airflow/models  
    command: celery worker
    depends_on:
      - airflow-init
      - postgres
      - redis

  airflow-init:
    image: apache/airflow:2.9.2
    build:
      context: .
    environment: *airflow_environment
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./requirements.txt:/requirements.txt
      - ./airflow.cfg:/opt/airflow/airflow.cfg
      - ./data:/opt/airflow/data  
      - ./models:/opt/airflow/models  
    entrypoint: bash -c "airflow db init && airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin"

  fastapi:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - redis
    restart: always
    volumes:
      - ./data:/appli/data
      - ./models:/appli/models

  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data

volumes:
  postgres-db-volume:
  
